// src/components/AITipDisplay.jsx - COMPLETE FILE
import React from 'react';
import ReactMarkdown from 'react-markdown'; // npm install react-markdown

const AITipDisplay = ({ tipContent }) => {
    return (
        <div className="ai-tip-display card fade-in">
            <h3 style={{color: 'var(--accent-color)', marginBottom: '15px'}}>Swing Sage AI Insights:</h3>
            <ReactMarkdown>{tipContent}</ReactMarkdown>
            <p className="note-text" style={{marginTop: '20px', fontSize: '0.9em'}}>
                *These tips are generated by AI. Always consult with a professional golf coach for personalized advice.
            </p>
        </div>
    );
};

export default AITipDisplay;